kind: Service
apiVersion: v1
metadata:
  name: mysql-headless
  namespace: expense
spec:
  clusterIP: None
  selector:
    purpose: expense
    component: mysql
    tier: db
  ports:
  - protocol: TCP
    port: 3306 # service port
    targetPort: 3306 # container port
---
kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    purpose: expense
    component: mysql
    tier: db
  ports:
  - protocol: TCP
    port: 3306 # service port
    targetPort: 3306 # container port
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    matchLabels:
      purpose: expense
      component: mysql
      tier: db # has to match .spec.template.metadata.labels
  serviceName: mysql-headless #this is headleess service which has to be mentioned for statefulset
  replicas: 3
  template:
    metadata:
      labels:
        purpose: expense
        component: mysql
        tier: db # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mysql
        image: yashdwar/mysql:v2
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
          #below is PVC def , can be written seperately also
  volumeClaimTemplates:
  - metadata:
      name: mysql
      namespace: expense
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "expense-ebs-voulmes"
      resources:
        requests:
          storage: 1Gi
